services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - secretKey=f43njkaBU670kdaoiu
    - PORT=5000
    - CLOUDINARY_URL=cloudinary://623643851873444:OY2A4wwoW1if6JTm7clxik2v7TY@prolite
    - DATABASE_URL=postgres://postgres:jordan@127.0.0.1:5432/prop_lite
    - TEST_DATABASE_URL=postgres://postgres:jordan@127.0.0.1:5432/db_test
language: node_js
node_js:
  - 10.15.3
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database prop_lite;' -U postgres
  - npm i
  - npm run copytest

script:
  - npm test
after_success:
  - npm run coverage