services:
  - postgresql
addons:
  postgresql: "5.5.1"
env:
  global:
    - secretKey=f43njkaBU670kdaoiu
    - PORT=5000
    - CLOUDINARY_URL=cloudinary://623643851873444:OY2A4wwoW1if6JTm7clxik2v7TY@prolite
    - DATABASE_URL=postgres://postgres:jordan@127.0.0.1:5432/prop_lite
  
language: node_js
node_js:
  - stable
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
  services:
    - postgresql
before_script:
  - psql -c 'CREATE DATABASE prop_lite;' -U postgres

script:
  - npm run test
after_success:
  - npm run coverage