language: node_js
node_js:
  - stable
branches:
  only:
    - develop
before_script :
 - psql -c 'CREATE DATABASE db_test;' -U postgres
script:
  - npm run test
after_success:
  - npm run coverage